version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TestAranda.2025*"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: ArandaTest.Api/Dockerfile
    container_name: ArandaApi
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConnectionAranda=Server=sqlserver;Database=ArandaTestDb;User Id=sa;Password=TestAranda.2025*;TrustServerCertificate=True;MultipleActiveResultSets=True;
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sql_data: